### ISSUE TITLE
API key update

### ISSUE THREAD

**Issue by claesmathias** [rmassch/healthbox-hacs#30]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/rmassch/healthbox3/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

First of all, amazing job! I don’t find the possibility to update the API key. If you configure it first without or need to renew in one year. 🙂

### Describe the solution you'd like

A setting in the services menu of Renson Healthbox

### Describe alternatives you've considered

Delete and reinstalling the service 

### Additional context

N/A

**Comment by rmassch** [comment]
Hey Mathias,

I'll look into how I can make it possible to update the config entry when I have some free time. For now you can just remove the integration and re-add it.
All sensors should remain the same (hopefully 😄)

**Comment by claesmathias** [comment]
Thanks. Would it be possible to contact you by mail? My mail address is ***@***.*** I have some questions around the VOC measurement and possible new feature requests.

________________________________

**Comment by rmassch** [comment]
I read up on the topic and I'll have to create an options flow.  So it's definitely possible but will require some free time on my part.

URL for my own reference later on
[Options Flow](https://developers.home-assistant.io/docs/config_entries_options_flow_handler/)

@claesmathias I don't like using e-mail. If you want you can open an issue for the VOC measurement (I doubt it's correct myself since I quickly googled how to convert the value). For feature requests you can also open them on Github.

However, if you want to communicate a different way, you can contact me on Discord which I check on occasion.
My Discord profile URL should be available on my Github profile.

**Comment by rmassch** [comment]
There's a beta version up. Please let me know if it works. It may be a bit wonky but it's the best I could do at this time with the documentation at hand. Might require a reload or 2 after the key is updated since the HB3 devices takes some time to validate
